### ISSUE TITLE
Unable to resolve resource file for resource wolf.qml for framework qt5

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-skill-wolfie#27]
```
~~~~:28.646 - gui - ovos_gui.namespace:_activate_namespace:752 - INFO - New namespace: skill-ovos-wolfie.openvoiceos
~~~~- ovos_gui.namespace:add:157 - INFO - GUI PROTOCOL - Adding "skill-ovos-wolfie.openvoiceos" to active namespaces
~~~~INFO - GUI PROTOCOL - Sending "skill-ovos-wolfie.openvoiceos" data -- wolfram_image : /tmp/how_complex_it_is.gif
~~~~327 - ERROR - Error updating qt5 client: Unable to resolve resource file for resource wolf.qml for framework qt5
Traceback (most recent call last):
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/namespace.py", line 325, in _add_pages
    client.send_gui_pages(new_pages, self.skill_id, position)
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/bus.py", line 272, in send_gui_pages
    "data": [{"url": page.get_uri(framework, server_url)}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/bus.py", line 272, in <listcomp>
    "data": [{"url": page.get_uri(framework, server_url)}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/page.py", line 86, in get_uri
    raise FileNotFoundError(f"Unable to resolve resource file for "
FileNotFoundError: Unable to resolve resource file for resource wolf.qml for framework qt5

```

**Comment by JarbasAl** [comment]
closed by https://github.com/OpenVoiceOS/ovos-skill-wolfie/pull/42
